name: riak-admin
version: 0.1.0.0

ghc-options: -Wall

default-extensions:
  - DeriveFunctor
  - FlexibleContexts
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - ViewPatterns

dependencies:
  - aeson >= 1.0
  - base
  - bytestring
  - data-default-class
  - exceptions
  - text

library:
  source-dirs: src
  dependencies:
    - async
    - megaparsec
    - process
    - reflection
    - safe-exceptions
    - text-format
  other-modules:
    - Control.Monad.Shell
    - Riak.Admin.Command.BucketType
    - Riak.Admin.Types
    - Riak.Admin.Types.BucketProps
    - Riak.Admin.Types.Internal

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - dlist
      - hspec
      - hspec-expectations
      - microlens
      - mtl
      - riak-admin
