name: monad-shell
version: 0.1.0.0

ghc-options: -Wall

default-extensions:
  - InstanceSigs
  - ViewPatterns

dependencies:
  - async
  - base
  - process
  - safe-exceptions
  - text
  - text-format

library:
  source-dirs: src
